### ISSUE TITLE
complex codeline

### ISSUE THREAD

**Issue by phtrong** [T-systemsYoungsters/dustin-LOGIST#6]
https://github.com/T-systemsYoungsters/dustin-LOGIST/blob/c30c827d427c520d9a216250b698a0101456c4a9/Tasks/31.01.22-04.02.22/python_chapter_5_lab.py#L34

can you please explain this codeline?

**Comment by DPlewa** [comment]
Es soll ein Rechteck gezeichnet werden.
'screen' ist die Fläche, auf welcher gezeichnet werden soll
'BLUE' ist die Farbe welche das Rechteck haben soll
'pygame.Rect': Hier werden die Parameter für das Rechteck mitgegeben
(30, 30, 60, 60) sind folgende Parameter: (x, y, width, height)

**Comment by phtrong** [comment]
kann man die Zeile auch ohne pygame.Rect benutzen ?
```python
 pygame.draw.rect(screen, BLUE, [30, 30, 60, 60]) 
```
und wenn ja was ist der Unterschied?
was macht pygame.Rect tatsächlich?

**Comment by phtrong** [comment]
Pygame.Rect wurde entfernt
