### ISSUE TITLE
Missing Tree?

### ISSUE THREAD

**Issue by phtrong** [T-systemsYoungsters/dustin-LOGIST#7]
https://github.com/T-systemsYoungsters/dustin-LOGIST/blob/c30c827d427c520d9a216250b698a0101456c4a9/Tasks/31.01.22-04.02.22/python_chapter_5_lab.py#L57

you are looping 3 times but only drawing 2 trees
it is you real intention to draw 2 trees ?

otherwise please check your code in line 64-65

**Comment by DPlewa** [comment]
Die 3 ist in der range() Funktion nicht inklusive

**Comment by phtrong** [comment]
aber range(3) loop 3 mal 
sollten es dann nicht drei sein ?

for i in range(3): print(i)

output: 0 1 2

**Comment by DPlewa** [comment]
Hast recht, er loopt drei mal. Aber wie du schon gesagt hast, von 0 - 2. Das heißt, der erste baum wird gar nicht gezeichnet. Habe es aber im Code so geändert, dass auch nur von 1 - 2 geloopt wird.

**Comment by DPlewa** [comment]
Im Loop werden die x-Parameter mit mit einem fixen Abstand (60) addiert. 60 wird mit i multipliziert. Entfernt man das i, werden drei Bäume gezeichnet, anstelle von nur 2. Es war grundsätzlich meine Absicht zwei Bäume zu zeichnen. Das i ist im ersten Loop 0, von daher sind die ersten im Loop veränderten x-Parameter von den Werten die selben wie die zuvor außerhalb des Loops definierten.

**Comment by phtrong** [comment]
Genau. Dadurch dass du die gleichen Werte hattest, wurde der erste Baum in der Zeichnung mit dem zweiten Baum überzeichnet und es sah so aus ob es nur 2 Bäume waren aber es waren tatsächlich drei. Durch die gleichen werte waren 2 übereinander.
